### ISSUE TITLE
Explain how to update the container image

### ISSUE THREAD

**Issue by olizilla** [web3-storage/backup-infra#6]
I assume I need to follow the steps here https://docs.aws.amazon.com/AmazonECR/latest/userguide/docker-push-ecr-image.html

**Comment by gobengo** [comment]
perhaps this? https://github.com/web3-storage/backup-infra/blob/main/terraspace/app/stacks/ecs-cluster/main.tf#L28

**Comment by gobengo** [comment]
https://github.com/web3-storage/backup-infra/blob/561603a2c30eda7c560683a996d5b92049e0422a/terraspace/app/stacks/ecs-cluster/tfvars/base.tfvars#L1

**Comment by olizilla** [comment]
ah, i meant "explain how to update and publish the image to the registry". This is mostly fixed by https://github.com/web3-storage/backup/pull/8 i just need to update the readme
